//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSEU.UI.Resources.Areas.Identity.Pages.Account.Manage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnableAuthenticator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnableAuthenticator() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DSEU.UI.Resources.Areas.Identity.Pages.Account.Manage.EnableAuthenticator", typeof(EnableAuthenticator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to и.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to чтобы использовать приложение проверки подлинности выполните следующие действия.
        /// </summary>
        public static string AuthenticatorAppSteps {
            get {
                return ResourceManager.GetString("AuthenticatorAppSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конфигурация приложения для аутентификации.
        /// </summary>
        public static string ConfigureAuthenticatorApp {
            get {
                return ResourceManager.GetString("ConfigureAuthenticatorApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скачать приложение для двухфакторной аутентификации, как Microsoft Authenticator для.
        /// </summary>
        public static string DownloadTwoFactorAuthenticator {
            get {
                return ResourceManager.GetString("DownloadTwoFactorAuthenticator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для.
        /// </summary>
        public static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to После того, как вы отсканировали QR-код или ввели ключ выше, ваше приложение двухфакторной аутентификации предоставит вам уникальный код. Введите код в поле подтверждения ниже..
        /// </summary>
        public static string OnceYouHaveScanned {
            get {
                return ResourceManager.GetString("OnceYouHaveScanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to или.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сканируйте QR-код или введите этот ключ.
        /// </summary>
        public static string ScanQrCode {
            get {
                return ResourceManager.GetString("ScanQrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код подтверждения.
        /// </summary>
        public static string VerificationCode {
            get {
                return ResourceManager.GetString("VerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверить.
        /// </summary>
        public static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to в вашем приложении двухфакторной аутентификации..
        /// </summary>
        public static string Your2FAAuthenticator {
            get {
                return ResourceManager.GetString("Your2FAAuthenticator", resourceCulture);
            }
        }
    }
}
