version: '3.4'

services:
   tthandicrafts:
     image: tthandicrafts
     container_name: tthandicrafts
     restart: always

   postgresdb:
    container_name: postgresdb
    image: postgres:latest
    restart: always

networks:
  tthandicrafts-network:
    driver: bridge

volumes:
  postgres-db-data: