//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTHandiCrafts.Infrastructure.Localizations.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages_tk {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages_tk() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TDS.Infrastructure.Localizations.Resources.Messages.tk", typeof(Messages_tk).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod boş bolup bilmez.
        /// </summary>
        internal static string AK_CodyCannotBeEmpty {
            get {
                return ResourceManager.GetString("AK_CodyCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kompaniýa boş bolup bilmez.
        /// </summary>
        internal static string AK_CompanyCannotBeEmpty {
            get {
                return ResourceManager.GetString("AK_CompanyCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ýurt boş bolup bilmez.
        /// </summary>
        internal static string AK_CountryCannotBeEmpty {
            get {
                return ResourceManager.GetString("AK_CountryCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir sebitden däl işgärler.
        /// </summary>
        internal static string AK_EmployeesNotFromSameRegion {
            get {
                return ResourceManager.GetString("AK_EmployeesNotFromSameRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sertifisirleme bölümiň ady boş bolup bilmez.
        /// </summary>
        internal static string AK_NameOfCertificationOrganizationCannotBeEmpty {
            get {
                return ResourceManager.GetString("AK_NameOfCertificationOrganizationCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belgi boş bolup bilmez.
        /// </summary>
        internal static string AK_NumberCannotBeEmtpy {
            get {
                return ResourceManager.GetString("AK_NumberCannotBeEmtpy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Önüm boş bolup bilmez.
        /// </summary>
        internal static string AK_ProductCannotBeEmpty {
            get {
                return ResourceManager.GetString("AK_ProductCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delilnama boş bolup bilmez.
        /// </summary>
        internal static string AK_RegulationCannotBeEmpty {
            get {
                return ResourceManager.GetString("AK_RegulationCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garaşly maglumatlary işlemekde ýalňyşlyk. Dogry doldurylandygyny barlaň.
        /// </summary>
        internal static string SK_CascadeDependencyError {
            get {
                return ResourceManager.GetString("SK_CascadeDependencyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sirkulýar mazmun anyklandy. Dogry doldurylandygyny barlaň..
        /// </summary>
        internal static string SK_CircularNesting {
            get {
                return ResourceManager.GetString("SK_CircularNesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maglumatlaryň dogrulygyny balaň..
        /// </summary>
        internal static string SK_EntityWithKeyDoesNotExists {
            get {
                return ResourceManager.GetString("SK_EntityWithKeyDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ýazgy eýýäm ulanýandygy sebäpli pozmak mümkin dal..
        /// </summary>
        internal static string SK_HasOneOreMoreDependencies {
            get {
                return ResourceManager.GetString("SK_HasOneOreMoreDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baha öňden bar.
        /// </summary>
        internal static string SK_ValueAlreadyExists {
            get {
                return ResourceManager.GetString("SK_ValueAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arzanyň belgisi boş bolup bilmez.
        /// </summary>
        internal static string SSDK_ApplicationIdCannotBeEmpty {
            get {
                return ResourceManager.GetString("SSDK_ApplicationIdCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nusgalar boş bolup bilmez.
        /// </summary>
        internal static string SSDK_SamplesCannotBeEmpty {
            get {
                return ResourceManager.GetString("SSDK_SamplesCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nusgalaryň saýlanan ýeri boş bolup bilmez.
        /// </summary>
        internal static string SSDK_SampleSelectionLocationCannotBeEmpty {
            get {
                return ResourceManager.GetString("SSDK_SampleSelectionLocationCannotBeEmpty", resourceCulture);
            }
        }
    }
}
