//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTHandiCrafts.Infrastructure.Localizations.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TDS.Infrastructure.Localizations.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код не может быть пустым.
        /// </summary>
        public static string AK_CodyCannotBeEmpty {
            get {
                return ResourceManager.GetString("AK_CodyCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компания не может быть пустой.
        /// </summary>
        public static string AK_CompanyCannotBeEmpty {
            get {
                return ResourceManager.GetString("AK_CompanyCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страна не может быть пустой.
        /// </summary>
        public static string AK_CountryCannotBeEmpty {
            get {
                return ResourceManager.GetString("AK_CountryCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сотрудники не из одного региона.
        /// </summary>
        public static string AK_EmployeesNotFromSameRegion {
            get {
                return ResourceManager.GetString("AK_EmployeesNotFromSameRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование отдела сертификации не может быть пустым.
        /// </summary>
        public static string AK_NameOfCertificationOrganizationCannotBeEmpty {
            get {
                return ResourceManager.GetString("AK_NameOfCertificationOrganizationCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер не может быть пустым.
        /// </summary>
        public static string AK_NumberCannotBeEmtpy {
            get {
                return ResourceManager.GetString("AK_NumberCannotBeEmtpy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продукт не может быть пустым.
        /// </summary>
        public static string AK_ProductCannotBeEmpty {
            get {
                return ResourceManager.GetString("AK_ProductCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нормативный акт не может быть пустым.
        /// </summary>
        public static string AK_RegulationCannotBeEmpty {
            get {
                return ResourceManager.GetString("AK_RegulationCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка обработки зависимых данных. Проверьте правильность заполнения.
        /// </summary>
        public static string SK_CascadeDependencyError {
            get {
                return ResourceManager.GetString("SK_CascadeDependencyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обнаружена циркулярная вложенность. Проверьте правильность заполнения данных..
        /// </summary>
        public static string SK_CircularNesting {
            get {
                return ResourceManager.GetString("SK_CircularNesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверьте правильность данных..
        /// </summary>
        public static string SK_EntityWithKeyDoesNotExists {
            get {
                return ResourceManager.GetString("SK_EntityWithKeyDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя удалять запись, так как она уже используется..
        /// </summary>
        public static string SK_HasOneOreMoreDependencies {
            get {
                return ResourceManager.GetString("SK_HasOneOreMoreDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение уже существует.
        /// </summary>
        public static string SK_ValueAlreadyExists {
            get {
                return ResourceManager.GetString("SK_ValueAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификатор заявления не может быть пустым.
        /// </summary>
        public static string SSDK_ApplicationIdCannotBeEmpty {
            get {
                return ResourceManager.GetString("SSDK_ApplicationIdCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Образцы не могут быть пустыми.
        /// </summary>
        public static string SSDK_SamplesCannotBeEmpty {
            get {
                return ResourceManager.GetString("SSDK_SamplesCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место выборки образцов не может быть пустым.
        /// </summary>
        public static string SSDK_SampleSelectionLocationCannotBeEmpty {
            get {
                return ResourceManager.GetString("SSDK_SampleSelectionLocationCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование акта не может быть пустым.
        /// </summary>
        public static string TLIK_NameActCannotBeEmpty {
            get {
                return ResourceManager.GetString("TLIK_NameActCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя лаборатории испытаний не может быть пустым.
        /// </summary>
        public static string TLIK_NameCannotBeEmpty {
            get {
                return ResourceManager.GetString("TLIK_NameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер акта не может быть пустым.
        /// </summary>
        public static string TLIK_NumberActCannotBeEmpty {
            get {
                return ResourceManager.GetString("TLIK_NumberActCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер акрредитации не может быть пустым.
        /// </summary>
        public static string TLIK_NumberCannotBeEmpty {
            get {
                return ResourceManager.GetString("TLIK_NumberCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат государственного инспектора не может быть пустым.
        /// </summary>
        public static string TLIK_ResultCannotBeEmpty {
            get {
                return ResourceManager.GetString("TLIK_ResultCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификатор документы по выборку товаров не может быть пустым.
        /// </summary>
        public static string TLIK_SampleSelectionDocumentIdCannotBeEmpty {
            get {
                return ResourceManager.GetString("TLIK_SampleSelectionDocumentIdCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результаты тестирования не может быть пустыми.
        /// </summary>
        public static string TLIK_TestResultsCannotBeEmpty {
            get {
                return ResourceManager.GetString("TLIK_TestResultsCannotBeEmpty", resourceCulture);
            }
        }
    }
}
