//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTHandiCrafts.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IdentityResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IdentityResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TTHandiCrafts.Resources.IdentityResources", typeof(IdentityResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для сброса пароля необходимо ввести код.
        /// </summary>
        public static string ACodeMustBeSuppliedForPasswordReset {
            get {
                return ResourceManager.GetString("ACodeMustBeSuppliedForPasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to поскольку в настоящее время он не включен..
        /// </summary>
        public static string AsitsNotCurrentlyEnabled {
            get {
                return ResourceManager.GetString("AsitsNotCurrentlyEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to так как они не имеют 2FA включен.
        /// </summary>
        public static string AsTheyDoNotHave2FAEnabled {
            get {
                return ResourceManager.GetString("AsTheyDoNotHave2FAEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно отключить 2FA для пользователя с идентификатором.
        /// </summary>
        public static string CannotDisable2FA {
            get {
                return ResourceManager.GetString("CannotDisable2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удается создать коды восстановления для пользователя с идентификатором.
        /// </summary>
        public static string CannotGenerateRecoveryCodesForUserWithID {
            get {
                return ResourceManager.GetString("CannotGenerateRecoveryCodesForUserWithID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите здесь.
        /// </summary>
        public static string ClickingHere {
            get {
                return ResourceManager.GetString("ClickingHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код не может быть пустым.
        /// </summary>
        public static string CodeIsNotShouldBeEmpty {
            get {
                return ResourceManager.GetString("CodeIsNotShouldBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий Пароль.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2- факторную авторизацию был отключен. Вы можете включить2- факторную авторизацию при установке приложение для проверки подлинности.
        /// </summary>
        public static string DisabledSucessfull {
            get {
                return ResourceManager.GetString("DisabledSucessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почта не должна быть пустой.
        /// </summary>
        public static string EmailIsNotShouldBeEmpty {
            get {
                return ResourceManager.GetString("EmailIsNotShouldBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный код аутентификатора, введенный для пользователя с идентификатором &apos;{UserId}&apos;.
        /// </summary>
        public static string InvalidAuthenticatorCodeEnteredForUserWithID {
            get {
                return ResourceManager.GetString("InvalidAuthenticatorCodeEnteredForUserWithID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста введите валидную почту.
        /// </summary>
        public static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный логин.
        /// </summary>
        public static string InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный введенный код восстановления.
        /// </summary>
        public static string InvalidRecoveryCodeEntered {
            get {
                return ResourceManager.GetString("InvalidRecoveryCodeEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старый пароль.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль и пароль подтверждения не совпадают..
        /// </summary>
        public static string PasswordDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль не должен быть пуст.
        /// </summary>
        public static string PasswordIsNotShouldBeEmpty {
            get {
                return ResourceManager.GetString("PasswordIsNotShouldBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, сбросьте свой пароль с помощью.
        /// </summary>
        public static string PleaseResetYourPasswordBy {
            get {
                return ResourceManager.GetString("PleaseResetYourPasswordBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сброс пароля.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий браузер был забыт. Когда вы снова войдете в систему из этого браузера вам будет предложено ввести свой код 2fa.
        /// </summary>
        public static string TheCurrentBrowserHasBeenForgotten {
            get {
                return ResourceManager.GetString("TheCurrentBrowserHasBeenForgotten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удается загрузить пользователя с двухфакторной аутентификацией.
        /// </summary>
        public static string UnableToLoadTwoFactorAuthenticationUser {
            get {
                return ResourceManager.GetString("UnableToLoadTwoFactorAuthenticationUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удается загрузить пользователя с идентификатором.
        /// </summary>
        public static string UnableToLoadUserWithID {
            get {
                return ResourceManager.GetString("UnableToLoadUserWithID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла непредвиденная ошибка при загрузке внешней регистрационной информации для пользователя с идентификатором.
        /// </summary>
        public static string UnexpectedErrorOccurred {
            get {
                return ResourceManager.GetString("UnexpectedErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла непредвиденная ошибка отключение 2FA для пользователя с идентификатором.
        /// </summary>
        public static string UnexpectedErrorOccurredDisabling2FAForUserWithID {
            get {
                return ResourceManager.GetString("UnexpectedErrorOccurredDisabling2FAForUserWithID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин не должен быть пустым.
        /// </summary>
        public static string UserNameIsNotShouldBeEmpty {
            get {
                return ResourceManager.GetString("UserNameIsNotShouldBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный код подтверждения.
        /// </summary>
        public static string VerificationCodeIsInvalid {
            get {
                return ResourceManager.GetString("VerificationCodeIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы создали новые коды восстановления.
        /// </summary>
        public static string YouHaveGeneratedNewRecoveryCodes {
            get {
                return ResourceManager.GetString("YouHaveGeneratedNewRecoveryCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше приложение Аутентификатор было проверено.
        /// </summary>
        public static string YourAuthenticatorAppHasBeenVerified {
            get {
                return ResourceManager.GetString("YourAuthenticatorAppHasBeenVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш ключ приложения authenticator был сброшен, вам нужно будет настроить свое приложение authenticator с помощью нового ключа.
        /// </summary>
        public static string YourAuthenticatorAppKeyHasBeenReset {
            get {
                return ResourceManager.GetString("YourAuthenticatorAppKeyHasBeenReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш пароль был изменен.
        /// </summary>
        public static string YourPasswordHasBeenChanged {
            get {
                return ResourceManager.GetString("YourPasswordHasBeenChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш пароль уже установлен.
        /// </summary>
        public static string YourPasswordHasBeenSet {
            get {
                return ResourceManager.GetString("YourPasswordHasBeenSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш профиль обновлен.
        /// </summary>
        public static string YourProfileHasBeenUpdated {
            get {
                return ResourceManager.GetString("YourProfileHasBeenUpdated", resourceCulture);
            }
        }
    }
}
